### ISSUE TITLE
Reconsider defaults within ds-branding

### ISSUE THREAD

**Issue by xjensen** [cagov/design-system#115]
I'm currently seeing some unexpected default behavior when using the ds-branding component on drought.ca.gov (in development). Here's a quick screenshot.

<img width="427" alt="Screen Shot 2021-09-10 at 09 18 07" src="https://user-images.githubusercontent.com/1208960/133133795-7fe289c5-2970-49e2-8db2-abd3d5922ba2.png">

Compare this to the current drought.ca.gov site below. (I believe the current drought site more-or-less matches what we want for design system defaults.)

<img width="413" alt="Screen Shot 2021-09-10 at 09 15 58" src="https://user-images.githubusercontent.com/1208960/133133988-e39a6807-e2b6-4f97-8f27-697610c88798.png">

We would need to make several edits to ds-branding to make the latter the default appearance of the component. How should we approach this, considering any changes here would have downstream consequences for headless.cannabis.ca.gov as well? Would any other sites be affected?

**Comment by xjensen** [comment]
I've come across a separate problem with the ds-dropdown-menu component on drought.ca.gov. The default padding in the component is squishing the menu headings onto separate lines.

<img width="868" alt="Screen Shot 2021-09-13 at 15 04 55" src="https://user-images.githubusercontent.com/1208960/133162677-2b107916-5730-4eca-825e-44a9f269ccab.png">

Compare to how this looks on the live drought.ca.gov site.

<img width="937" alt="Screen Shot 2021-09-13 at 15 06 21" src="https://user-images.githubusercontent.com/1208960/133162760-6ad287f7-7b22-47ff-9ebb-b98b3e5756b0.png">

This difference seems to be due to the following CSS rule.

```css
@media (min-width: 768px) {
    cagov-navoverlay .expanded-menu-section-header-link {
        width:auto;
        padding-right: 2rem
    }
}
```

I'm hoping we can modify the ds-dropdown-menu component to allow room for these longer labels.

**Comment by xjensen** [comment]
Found a small thing in ds-statewide-header.

```css
.ofiicial-logo {
    /* stuff */
}
```

We should probably rename `ofiicial-logo` to `official-logo`. I spent way too long banging my head on this naming conflict when trying to implement this component in drought.ca.gov.

**Comment by xjensen** [comment]
There's a difference in CA.GOV logo colors between ds-statewide-header and ds-statewide-footer. This difference does not appear on headless.cannabis.ca.gov, but it does seem to show up via the drought.ca.gov color scheme.

ds-statewide-header:
```css
svg {
    /* stuff */
    .ca {
        fill: var(--secondary-color, #cf5d28);
    }
    .gov {
        fill: var(--primary-dark-color, #4a1106);
    }
}
```

ds-statewide-footer:
```css
.bg-light-grey svg {
    /* stuff */
    .ca {
        fill: var(--highlight-color, #FEC02F);
    }
    .gov {
        fill: var(--primary-color, #004ABC);
    }
}
```

Not sure if we're concerned with this. Pointing it out, just in case.
