### ISSUE TITLE
CA.GOV logo colors differ between ds-statewide-header and ds-statewide-footer

### ISSUE THREAD

**Issue by xjensen** [cagov/design-system#121]
Among design-system components, there's a difference in CA.GOV logo colors between ds-statewide-header and ds-statewide-footer. This difference does not appear on headless.cannabis.ca.gov, but it does seem to show up when implementing default design-system on drought.ca.gov.

## Visual differences

For the header logo, CA is using the secondary color, while GOV is using the primary dark color.
<img width="505" alt="Screen Shot 2021-09-14 at 12 05 34" src="https://user-images.githubusercontent.com/1208960/133318761-75e63530-4d86-4057-be89-ab4271e69019.png">

For the footer logo, CA is using the highlight color, while GOV is using the primary color.
<img width="605" alt="Screen Shot 2021-09-14 at 12 06 58" src="https://user-images.githubusercontent.com/1208960/133318883-d457737f-85b0-4721-b7df-fe641dd2c8e1.png">

## Relevant code

ds-statewide-header:
```css
svg {
    /* stuff */
    .ca {
        fill: var(--secondary-color, #cf5d28);
    }
    .gov {
        fill: var(--primary-dark-color, #4a1106);
    }
}
```

ds-statewide-footer:
```css
.bg-light-grey svg {
    /* stuff */
    .ca {
        fill: var(--highlight-color, #FEC02F);
    }
    .gov {
        fill: var(--primary-color, #004ABC);
    }
}
```

## Request

@adam-little, I'm wondering if this is by design. If not, I'm wondering which combination of colors should be applied in either or both cases.
